# Generated by Django 4.0.5 on 2022-06-14 07:21

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields

from company.gen_master_data import gen_master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('company_name', models.CharField(max_length=50, verbose_name='회사명')),
                ('country', models.CharField(max_length=50, verbose_name='국가')),
                ('region', models.CharField(max_length=50, verbose_name='지역')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_name'], name='company_name_idx'),
        ),
        migrations.RunPython(gen_master)
    ]
